name: Hickory On-Demand Status

on:
  workflow_dispatch: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Status to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            📣 **Hickory – napi státusz**

            • Wallet: specifikáció/UX váz szükséges, API-szerződés előkészítése folyamatban. ⟨confirm⟩
            • HICScan: indexer + sémák tervezése indul; első block/tx lekérdezések PoC. ⟨confirm⟩
            • HickoryDex: MVP-scope (pool, swap, liquidity) definiálás előtt. ⟨confirm⟩
            • Backend: /version + /health, OpenAPI stub, Dockerize → következő sprint fókusz.
            • Infra: Discord értesítések (push/PR/merge), Weekly & On-demand report **aktív**; main védett (PR-kötelező); CODEOWNERS él.
            • Whitepaper/Funding: outline + deck v1 hiányzik, data room előkészítendő. ⟨confirm⟩
            • Docs: Docusaurus/MkDocs keret + ADR napló bevezetése.

            👤 **Felelősök**
            – Lara: Wallet UX/UI + kliens váz
            – Bob: Backend/API + indexer PoC
            – Lucy: HICScan explorer
            – Suzy: Docs/QA + riportok
            – Co-CEO: Funding/Partners

            ⏭️ **Next 48h**
            1) Repo baseline (docs, contributing, release tags)
            2) Backend OpenAPI + Dockerfile
            3) Wallet flow & szerződés
            4) Explorer PoC első végpontok
            5) Riport metrikák bővítése (issues/releases)
